import assert from 'node:assert/strict';
import test from 'node:test';
import {calculateSecurityScore,redactSecurityData,securityCapabilities,securityFindings,securityModule,securityOverview,securityRecommendations} from '../src/security/security-center.js';
import {SecurityStore} from '../src/security/security-store.js';
import type {RouterSnapshot} from '../src/types.js';

const snapshot:RouterSnapshot={timestamp:'2026-07-18T00:00:00.000Z',stale:false,authentication:{status:'connected',reason:null,verifiedEndpoint:'/index.asp'},deviceInfo:{supported:true,reason:null,sourceEndpoint:'/device',lastUpdated:null,model:'LG8245X6-10',firmware:'V5',serial:null,hardwareVersion:null,uptime:null},health:{supported:false,reason:null,sourceEndpoint:null,lastUpdated:null,cpuUsage:null,memoryUsage:null,temperature:null},wan:{supported:true,reason:null,sourceEndpoint:'/wan',lastUpdated:null,state:'Connected',ip:'203.0.113.2',gateway:null,dns:['1.1.1.1'],connectionType:null,uptime:null,uploadBytes:null,downloadBytes:null},wifi:{supported:true,reason:null,sourceEndpoint:'/wifi',lastUpdated:null,bands:[{band:'2.4 GHz',ssid:'VerifiedSSID',enabled:true,channel:6,security:null,guest:false}]},devices:{supported:true,reason:null,sourceEndpoint:'/devices',lastUpdated:null,items:[]},security:{supported:false,reason:null,sourceEndpoint:null,lastUpdated:null,firewall:null,macFilter:null,dmz:null,upnp:null}};

test('capabilities separate verified reads from unverified writes',()=>{const caps=securityCapabilities(snapshot);assert.equal(caps.routerManagementProtected.verified,true);assert.equal(caps.firewallWrite.supported,false);assert.equal(caps.firewallWrite.verified,false);assert.equal(caps.firewallWrite.readOnly,true)});
test('partial score counts only verified evidence',()=>{const score=calculateSecurityScore(snapshot);assert.equal(score.kind,'partial');assert.equal(score.score,100);assert.equal(score.verifiedControls,2);assert.equal(score.totalAssessedControls,4);assert.equal(score.confidence,'low');assert.match(score.message??'',/Insufficient verified data/)});
test('unknown controls never become findings or fabricated alerts',()=>{assert.deepEqual(securityFindings(snapshot),[]);assert.deepEqual(securityOverview(snapshot).alerts,[]);assert.equal(securityModule('firewall',snapshot).supported,false)});
test('recommendations are deterministic and clearly unverified',()=>{const first=securityRecommendations(snapshot);assert.deepEqual(first,securityRecommendations(snapshot));assert.equal(first.every(item=>item.automaticRemediationSupported===false),true);assert.equal(first.some(item=>item.risk==='Unknown until verified'),true)});
test('security redaction recursively removes sensitive values',()=>{assert.deepEqual(redactSecurityData({username:'admin',password:'x',headers:{cookie:'sid=x',accept:'json'},tokens:['visible only because key is sensitive']}),{username:'admin',password:'[REDACTED]',headers:{cookie:'[REDACTED]',accept:'json'},tokens:'[REDACTED]'})});
test('score history persists without credentials or invented fields',async()=>{const store=new SecurityStore(':memory:');await store.init();await store.recordScore(snapshot.timestamp,100,2,'low');const rows=await store.history();assert.equal(rows.length,1);assert.equal(rows[0]?.score,100);assert.equal(rows[0]?.verifiedControls,2);assert.equal('password' in (rows[0]??{}),false)});
