import type { RouterAuth } from '@adil-routeros/shared';
import { getRouterRuntimeConfig } from '../config.js';
import type { AuthDiagnosticStage, DeviceSnapshot, RouterSnapshot, SafeDiagnostic, SupportMeta } from '../types.js';

export const encodeHuaweiPassword = (password:string):string => Buffer.from(password,'utf8').toString('base64').replace(/=+$/,'');
export const parseCookiePair = (cookie:string):[string,string]|null => {const pair=cookie.split(';',1)[0];const index=pair.indexOf('=');return index>0?[pair.slice(0,index).trim(),pair.slice(index+1).trim()]:null};
export const isLoginPage = (body:string):boolean => /(?:name=["']UserName|\/login\.cgi|safelogin\.js)/i.test(body);
export const verifyProtectedResponse = (status:number, body:string):boolean => status===200 && !isLoginPage(body) && (/(?:getWanDynamicData\.asp|CustomApp\/mainpage\.asp|frameaspdes|id=["']menu|<frameset|name=["'](?:mainFrame|contentFrame))/i.test(body));

const decode=(v:string)=>v.replace(/\\(['"\\])/g,'$1').replace(/\\x([0-9a-f]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16)));
const args=(text:string):string[]=>{const out:string[]=[]; let cur='',q='',esc=false,depth=0; for(const ch of text){if(esc){cur+=ch;esc=false;continue} if(ch==='\\'){cur+=ch;esc=true;continue} if(q){cur+=ch;if(ch===q)q='';continue} if(ch==='"'||ch==="'"){q=ch;cur+=ch;continue} if(ch==='('){depth++;cur+=ch;continue} if(ch===')'){depth--;cur+=ch;continue} if(ch===','&&depth===0){out.push(cur.trim());cur='';continue} cur+=ch} out.push(cur.trim()); return out.map(v=>{const m=v.match(/^(['"])([\s\S]*)\1$/);return m?decode(m[2]):v==='null'?'':v});};
export const constructorRows=(body:string,name:string):string[][]=>[...body.matchAll(new RegExp(`new\\s+${name}\\s*\\(([^;]*?)\\)(?=\\s*[,;)]|$)`,'g'))].map(m=>args(m[1]));
const first=(body:string,names:string[])=>{for(const n of names){const row=constructorRows(body,n)[0];if(row)return row}return null};
const bool=(v?:string)=>v==null||v===''?null:/^(1|true|enable|enabled|up|online)$/i.test(v)?true:/^(0|false|disable|disabled|down|offline)$/i.test(v)?false:null;
const num=(v?:string)=>v!=null&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
const meta=(supported:boolean,endpoint:string,now:string,reason='No mapped values were exposed by this firmware response'):SupportMeta=>({supported,reason:supported?null:reason,sourceEndpoint:endpoint,lastUpdated:supported?now:null});

export const parseDeviceInfo=(body:string,now=new Date().toISOString())=>{const r=first(body,['stDeviceInfo']); const value={model:r?.[4]||null,firmware:r?.[3]||null,serial:r?.[1]||null,hardwareVersion:r?.[2]||null,uptime:null}; const ok=Object.values(value).some(v=>v!=null); return {...meta(ok,'/html/ssmp/deviceinfo/deviceinfo.asp',now),...value}};
export const parseDevices=(body:string,now=new Date().toISOString())=>{const rows=[...constructorRows(body,'USERDeviceNew'),...constructorRows(body,'USERDevice')]; const items:DeviceSnapshot[]=rows.filter(r=>r[2]).map(r=>({hostname:r[9]||null,alias:r[13]||null,ipv4:r[1]||null,ipv6:null,mac:(r[16]||r[2]).toUpperCase().replace(/-/g,':'),connectionType:r[7]||null,wifiBand:/5G/i.test(r[7]||r[3])?'5 GHz':/wifi|ssid/i.test(r[7]||r[3])?'2.4 GHz':null,signal:null,online:bool(r[6]),connectionDuration:num(r[8])})); return {...meta(items.length>0,'/html/bbsp/common/GetLanUserDevInfo.asp',now,'No connected-device constructor rows were exposed'),items}};
export const parseWifi=(body:string,now=new Date().toISOString())=>{const rows=[...constructorRows(body,'stWlan'),...constructorRows(body,'stWlanWifi')]; const bands=rows.filter(r=>r[3]).map((r,i)=>({band:(/5g/i.test(r[0]+' '+r[1])||i>0?'5 GHz':'2.4 GHz') as '2.4 GHz'|'5 GHz',ssid:r[3]||null,enabled:bool(r[2]),channel:num(r[5]),security:null,guest:/guest/i.test(r[1]||r[0])})); return {...meta(bands.length>0,'/html/amp/wlanadv/wlanadvance_api.asp',now,'No SSID constructor rows were exposed'),bands}};
export const parseWan=(body:string,now=new Date().toISOString())=>{const candidates=['stWanInfo','WanInfo','stWan','WANIPConnection','WANPPPConnection'].flatMap(n=>constructorRows(body,n)); const r=candidates.find(x=>x.some(v=>/\b(?:\d{1,3}\.){3}\d{1,3}\b/.test(v)))||candidates[0]; const ip=r?.find(v=>/^(?:\d{1,3}\.){3}\d{1,3}$/.test(v))||null; const state=r?.find(v=>/^(connected|disconnected|up|down)$/i.test(v))||null; const dns=r?.find(v=>/(?:\d{1,3}\.){3}\d{1,3}[, ]+(?:\d{1,3}\.){3}\d{1,3}/.test(v)); const value={state,ip,gateway:null,dns:dns?dns.split(/[, ]+/):null,connectionType:null,uptime:null,uploadBytes:null,downloadBytes:null}; const ok=Object.values(value).some(v=>v!=null); return {...meta(ok,'/html/bbsp/common/getWanDynamicData.asp',now),...value}};

class CookieJar {
 private jar=new Map<string,string>();
 clear(){this.jar.clear()}
 set(name:string,value:string){this.jar.set(name,value)}
 setHeaders(headers:Headers){const values=(headers as Headers & {getSetCookie?:()=>string[]}).getSetCookie?.()??[];for(const cookie of values){const pair=parseCookiePair(cookie);if(pair)this.jar.set(pair[0],pair[1])}return values.length}
 header(){return [...this.jar].map(([k,v])=>`${k}=${v}`).join('; ')}
 count(){return this.jar.size}
}
interface ResponseData{status:number;body:string;contentType:string|null;location:string|null;cookiesReceived:number}
interface RequestInit { method?: string; headers?: Record<string,string> | Headers; body?: string | URLSearchParams; accept?:'ajax'|'document' }
const endpoints={device:{path:'/html/ssmp/deviceinfo/deviceinfo.asp',method:'GET',referer:'/index.asp'},devices:{path:'/html/bbsp/common/GetLanUserDevInfo.asp',method:'GET',referer:'/CustomApp/mainpage.asp'},wan:{path:'/html/bbsp/common/getWanDynamicData.asp',method:'GET',referer:'/index.asp'},wifi:{path:'/html/amp/wlanadv/wlanadvance_api.asp',method:'GET',referer:'/html/amp/wlanadv/WlanAdvance.asp'}} as const;

export class HuaweiClient {
 private config=getRouterRuntimeConfig(); private cookies=new CookieJar(); private auth:RouterAuth|null=null; private authenticated=false; private stages:AuthDiagnosticStage[]=[]; private diagnostic:SafeDiagnostic={stage:'idle',endpoint:null,httpStatus:null,contentType:null,responseLength:null,authenticated:false,reason:null,parserName:null,lastPollTime:null};
 private async request(path:string,init:RequestInit={}):Promise<ResponseData>{const h=new Headers(init.headers);h.set('Accept',init.accept==='ajax'?'*/*':'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7');h.set('Accept-Language','en-US,en;q=0.9');h.set('User-Agent','Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36');const c=this.cookies.header();if(c)h.set('Cookie',c);const {accept:_,...fetchInit}=init;void _;const res=await fetch(new URL(path,this.config.baseUrl),{...fetchInit,headers:h,redirect:'manual',signal:AbortSignal.timeout(this.config.requestTimeoutMs)});const cookiesReceived=this.cookies.setHeaders(res.headers);return{status:res.status,body:await res.text(),contentType:res.headers.get('content-type'),location:res.headers.get('location'),cookiesReceived}}
 private note(stage:string,endpoint:string,r:ResponseData,authenticated:boolean,reason:string|null,parserName:string|null=null){this.diagnostic={stage,endpoint,httpStatus:r.status,contentType:r.contentType,responseLength:r.body.length,authenticated,reason,parserName,lastPollTime:this.diagnostic.lastPollTime}}
 private authStage(stage:string,endpoint:string,method:string,r:ResponseData,authenticated:boolean,reason:string|null){this.stages.push({stage,endpoint,method,httpStatus:r.status,cookiesReceived:r.cookiesReceived,cookiesStored:this.cookies.count(),redirectTarget:r.location?new URL(r.location,this.config.baseUrl).pathname:null,authenticated,reason,timestamp:new Date().toISOString()})}
 async connect(auth:RouterAuth){this.auth={...auth};this.cookies.clear();this.stages=[];this.authenticated=false;const origin=new URL(this.config.baseUrl).origin;const root=await this.request('/');this.note('initial','/',root,false,null);this.authStage('initial-page','/','GET',root,false,null);if(root.status===429)throw new Error('Router rate limit');const rand=await this.request('/asp/GetRandCount.asp',{method:'POST',accept:'ajax',headers:{Origin:origin,Referer:`${origin}/`}});this.note('challenge','/asp/GetRandCount.asp',rand,false,null);this.authStage('random-token','/asp/GetRandCount.asp','POST',rand,false,rand.body.trim()?'Token received':'Invalid token');const token=rand.body.trim();if(!token)throw new Error('Invalid token');this.cookies.set('Cookie','body:Language:english:id=-1');const form=new URLSearchParams({UserName:auth.username,PassWord:encodeHuaweiPassword(auth.password),Language:'english','x.X_HW_Token':token});const login=await this.request('/login.cgi',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Origin:origin,Referer:`${origin}/`},body:form});this.note('login','/login.cgi',login,false,null);this.authStage('login-request','/login.cgi','POST',login,false,login.status===200?null:`Login HTTP ${login.status}`);if(login.status===429)throw new Error('Router rate limit');if(login.status!==200)throw new Error('Protocol mismatch');const protectedPage=await this.request(login.location||'/index.asp',{method:'GET',headers:{Referer:`${origin}/login.cgi`}});const verified=verifyProtectedResponse(protectedPage.status,protectedPage.body);let reason:string|null=null;if(protectedPage.status===429)reason='Router rate limit';else if(protectedPage.status===403)reason='Protected endpoint forbidden';else if(protectedPage.status===401||isLoginPage(protectedPage.body))reason='Credentials rejected';else if(!verified)reason='Protocol mismatch';this.note('verification','/index.asp',protectedPage,verified,reason);this.authStage('protected-verification','/index.asp','GET',protectedPage,verified,reason);if(!verified)throw new Error(reason??'Protocol mismatch');const data=await this.request('/html/bbsp/common/getWanDynamicData.asp',{method:'GET',headers:{Referer:`${origin}/index.asp`}});const dataVerified=data.status===200&&!isLoginPage(data.body)&&data.body.length>0;const dataReason=dataVerified?null:data.status===403?'Protected endpoint forbidden':isLoginPage(data.body)?'Session expired':'Protocol mismatch';this.authStage('protected-data','/html/bbsp/common/getWanDynamicData.asp','GET',data,dataVerified,dataReason);if(!dataVerified)throw new Error(dataReason??'Protocol mismatch');this.authenticated=true;this.note('verification','/html/bbsp/common/getWanDynamicData.asp',data,true,null,'parseWan')}
 async disconnect(){this.cookies.clear();this.auth=null;this.authenticated=false}
 getDiagnostics(){return {...this.diagnostic}}
 getAuthDiagnostics(){return this.stages.map(stage=>({...stage}))}
 async getSnapshot():Promise<RouterSnapshot>{if(!this.authenticated){if(!this.auth)throw new Error('Authentication required');await this.connect(this.auth)} const now=new Date().toISOString(); const read=async(key:keyof typeof endpoints)=>{const e=endpoints[key];const r=await this.request(e.path,{method:e.method,headers:{Referer:new URL(e.referer,this.config.baseUrl).toString()}});if(isLoginPage(r.body)){this.authenticated=false;throw new Error('Session expired')}this.note('poll',e.path,r,true,null,`parse${key[0].toUpperCase()+key.slice(1)}`);return r.body}; const [d,dev,w,wi]=await Promise.all([read('device'),read('devices'),read('wan'),read('wifi')]); this.diagnostic.lastPollTime=now; return{timestamp:now,stale:false,authentication:{status:'connected',reason:null,verifiedEndpoint:'/index.asp'},deviceInfo:parseDeviceInfo(d,now),health:{...meta(false,'/html/ssmp/deviceinfo/deviceinfo.asp',now,'CPU, memory and temperature are not exposed by captured endpoints'),cpuUsage:null,memoryUsage:null,temperature:null},wan:parseWan(w,now),wifi:parseWifi(wi,now),devices:parseDevices(dev,now),security:{...meta(false,'/html/bbsp/firewalllog/firewalllogview.asp',now,'Security status values were not verified in the captures'),firewall:null,macFilter:null,dmz:null,upnp:null}}}
}
export class HuaweiDriver extends HuaweiClient {}
export class HuaweiDriverFactory{create(){return new HuaweiDriver()}}
