import type { RouterAuth } from '@adil-routeros/shared';
import { getRouterRuntimeConfig } from '../config.js';
import type { DeviceSnapshot, RouterSnapshot, SafeDiagnostic, SupportMeta } from '../types.js';

export const splitSetCookie = (value:string):string[] => value.split(/,(?=\s*[^;,=\s]+=[^;,]*)/).map(v=>v.trim()).filter(Boolean);
export const isLoginPage = (body:string):boolean => /(?:name=["']UserName|\/login\.cgi|safelogin\.js)/i.test(body);
export const verifyProtectedResponse = (status:number, body:string):boolean => status===200 && !isLoginPage(body) && (/(?:getWanDynamicData\.asp|CustomApp\/mainpage\.asp|frameaspdes|id=["']menu|<frameset|name=["'](?:mainFrame|contentFrame))/i.test(body));

const decode=(v:string)=>v.replace(/\\(['"\\])/g,'$1').replace(/\\x([0-9a-f]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16)));
const args=(text:string):string[]=>{const out:string[]=[]; let cur='',q='',esc=false,depth=0; for(const ch of text){if(esc){cur+=ch;esc=false;continue} if(ch==='\\'){cur+=ch;esc=true;continue} if(q){cur+=ch;if(ch===q)q='';continue} if(ch==='"'||ch==="'"){q=ch;cur+=ch;continue} if(ch==='('){depth++;cur+=ch;continue} if(ch===')'){depth--;cur+=ch;continue} if(ch===','&&depth===0){out.push(cur.trim());cur='';continue} cur+=ch} out.push(cur.trim()); return out.map(v=>{const m=v.match(/^(['"])([\s\S]*)\1$/);return m?decode(m[2]):v==='null'?'':v});};
export const constructorRows=(body:string,name:string):string[][]=>[...body.matchAll(new RegExp(`new\\s+${name}\\s*\\(([^;]*?)\\)(?=\\s*[,;)]|$)`,'g'))].map(m=>args(m[1]));
const first=(body:string,names:string[])=>{for(const n of names){const row=constructorRows(body,n)[0];if(row)return row}return null};
const bool=(v?:string)=>v==null||v===''?null:/^(1|true|enable|enabled|up|online)$/i.test(v)?true:/^(0|false|disable|disabled|down|offline)$/i.test(v)?false:null;
const num=(v?:string)=>v!=null&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
const meta=(supported:boolean,endpoint:string,now:string,reason='No mapped values were exposed by this firmware response'):SupportMeta=>({supported,reason:supported?null:reason,sourceEndpoint:endpoint,lastUpdated:supported?now:null});

export const parseDeviceInfo=(body:string,now=new Date().toISOString())=>{const r=first(body,['stDeviceInfo']); const value={model:r?.[4]||null,firmware:r?.[3]||null,serial:r?.[1]||null,hardwareVersion:r?.[2]||null,uptime:null}; const ok=Object.values(value).some(v=>v!=null); return {...meta(ok,'/html/ssmp/deviceinfo/deviceinfo.asp',now),...value}};
export const parseDevices=(body:string,now=new Date().toISOString())=>{const rows=[...constructorRows(body,'USERDeviceNew'),...constructorRows(body,'USERDevice')]; const items:DeviceSnapshot[]=rows.filter(r=>r[2]).map(r=>({hostname:r[9]||null,alias:r[13]||null,ipv4:r[1]||null,ipv6:null,mac:(r[16]||r[2]).toUpperCase().replace(/-/g,':'),connectionType:r[7]||null,wifiBand:/5G/i.test(r[7]||r[3])?'5 GHz':/wifi|ssid/i.test(r[7]||r[3])?'2.4 GHz':null,signal:null,online:bool(r[6]),connectionDuration:num(r[8])})); return {...meta(items.length>0,'/html/bbsp/common/GetLanUserDevInfo.asp',now,'No connected-device constructor rows were exposed'),items}};
export const parseWifi=(body:string,now=new Date().toISOString())=>{const rows=[...constructorRows(body,'stWlan'),...constructorRows(body,'stWlanWifi')]; const bands=rows.filter(r=>r[3]).map((r,i)=>({band:(/5g/i.test(r[0]+' '+r[1])||i>0?'5 GHz':'2.4 GHz') as '2.4 GHz'|'5 GHz',ssid:r[3]||null,enabled:bool(r[2]),channel:num(r[5]),security:null,guest:/guest/i.test(r[1]||r[0])})); return {...meta(bands.length>0,'/html/amp/wlanadv/wlanadvance_api.asp',now,'No SSID constructor rows were exposed'),bands}};
export const parseWan=(body:string,now=new Date().toISOString())=>{const candidates=['stWanInfo','WanInfo','stWan','WANIPConnection','WANPPPConnection'].flatMap(n=>constructorRows(body,n)); const r=candidates.find(x=>x.some(v=>/\b(?:\d{1,3}\.){3}\d{1,3}\b/.test(v)))||candidates[0]; const ip=r?.find(v=>/^(?:\d{1,3}\.){3}\d{1,3}$/.test(v))||null; const state=r?.find(v=>/^(connected|disconnected|up|down)$/i.test(v))||null; const dns=r?.find(v=>/(?:\d{1,3}\.){3}\d{1,3}[, ]+(?:\d{1,3}\.){3}\d{1,3}/.test(v)); const value={state,ip,gateway:null,dns:dns?dns.split(/[, ]+/):null,connectionType:null,uptime:null,uploadBytes:null,downloadBytes:null}; const ok=Object.values(value).some(v=>v!=null); return {...meta(ok,'/html/bbsp/common/getWanDynamicData.asp',now),...value}};

class CookieJar { private jar=new Map<string,string>(); clear(){this.jar.clear()} setHeaders(headers:Headers){const values=(headers as Headers & {getSetCookie?:()=>string[]}).getSetCookie?.()??splitSetCookie(headers.get('set-cookie')??''); for(const c of values){const pair=c.split(';',1)[0]; const i=pair.indexOf('=');if(i>0)this.jar.set(pair.slice(0,i).trim(),pair.slice(i+1).trim())}} header(){return [...this.jar].map(([k,v])=>`${k}=${v}`).join('; ')}}
interface ResponseData{status:number;body:string;contentType:string|null;location:string|null}
interface RequestInit { method?: string; headers?: Record<string,string> | Headers; body?: string | URLSearchParams }
const endpoints={device:{path:'/html/ssmp/deviceinfo/deviceinfo.asp',method:'GET',referer:'/index.asp'},devices:{path:'/html/bbsp/common/GetLanUserDevInfo.asp',method:'GET',referer:'/CustomApp/mainpage.asp'},wan:{path:'/html/bbsp/common/getWanDynamicData.asp',method:'GET',referer:'/index.asp'},wifi:{path:'/html/amp/wlanadv/wlanadvance_api.asp',method:'GET',referer:'/html/amp/wlanadv/WlanAdvance.asp'}} as const;

export class HuaweiClient {
 private config=getRouterRuntimeConfig(); private cookies=new CookieJar(); private auth:RouterAuth|null=null; private authenticated=false; private diagnostic:SafeDiagnostic={stage:'idle',endpoint:null,httpStatus:null,contentType:null,responseLength:null,authenticated:false,reason:null,parserName:null,lastPollTime:null};
 private async request(path:string,init:RequestInit={}):Promise<ResponseData>{const h=new Headers(init.headers);h.set('Accept','text/html,application/xhtml+xml,*/*'); const c=this.cookies.header();if(c)h.set('Cookie',c); const res=await fetch(new URL(path,this.config.baseUrl),{...init,headers:h,redirect:'manual',signal:AbortSignal.timeout(this.config.requestTimeoutMs)});this.cookies.setHeaders(res.headers);return{status:res.status,body:await res.text(),contentType:res.headers.get('content-type'),location:res.headers.get('location')}}
 private note(stage:string,endpoint:string,r:ResponseData,authenticated:boolean,reason:string|null,parserName:string|null=null){this.diagnostic={stage,endpoint,httpStatus:r.status,contentType:r.contentType,responseLength:r.body.length,authenticated,reason,parserName,lastPollTime:this.diagnostic.lastPollTime}}
 async connect(auth:RouterAuth){this.auth={...auth};this.cookies.clear();this.authenticated=false; const root=await this.request('/'); this.note('initial','/',root,false,null); const rand=await this.request('/asp/GetRandCount.asp',{method:'POST',headers:{Referer:new URL('/',this.config.baseUrl).toString()}}); this.note('challenge','/asp/GetRandCount.asp',rand,false,null); const token=rand.body.trim(); const form=new URLSearchParams({UserName:auth.username,PassWord:auth.password,Language:'english','x.X_HW_Token':token}); const login=await this.request('/login.cgi',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Referer:new URL('/',this.config.baseUrl).toString()},body:form}); this.note('login','/login.cgi',login,false,null); if(login.status!==200)throw new Error('Authentication failed'); const protectedPage=await this.request(login.location||'/index.asp',{method:'GET',headers:{Referer:new URL('/',this.config.baseUrl).toString()}}); const verified=verifyProtectedResponse(protectedPage.status,protectedPage.body); const rejected=protectedPage.status===401||protectedPage.status===403||isLoginPage(protectedPage.body); this.note('verification','/index.asp',protectedPage,verified,verified?null:rejected?'Credentials rejected by protected endpoint':'Firmware protocol mismatch'); if(!verified)throw new Error(rejected?'Authentication failed':'Protocol mismatch');this.authenticated=true}
 async disconnect(){this.cookies.clear();this.auth=null;this.authenticated=false}
 getDiagnostics(){return {...this.diagnostic}}
 async getSnapshot():Promise<RouterSnapshot>{if(!this.authenticated){if(!this.auth)throw new Error('Authentication required');await this.connect(this.auth)} const now=new Date().toISOString(); const read=async(key:keyof typeof endpoints)=>{const e=endpoints[key];const r=await this.request(e.path,{method:e.method,headers:{Referer:new URL(e.referer,this.config.baseUrl).toString()}});if(isLoginPage(r.body)){this.authenticated=false;throw new Error('Session expired')}this.note('poll',e.path,r,true,null,`parse${key[0].toUpperCase()+key.slice(1)}`);return r.body}; const [d,dev,w,wi]=await Promise.all([read('device'),read('devices'),read('wan'),read('wifi')]); this.diagnostic.lastPollTime=now; return{timestamp:now,stale:false,authentication:{status:'connected',reason:null,verifiedEndpoint:'/index.asp'},deviceInfo:parseDeviceInfo(d,now),health:{...meta(false,'/html/ssmp/deviceinfo/deviceinfo.asp',now,'CPU, memory and temperature are not exposed by captured endpoints'),cpuUsage:null,memoryUsage:null,temperature:null},wan:parseWan(w,now),wifi:parseWifi(wi,now),devices:parseDevices(dev,now),security:{...meta(false,'/html/bbsp/firewalllog/firewalllogview.asp',now,'Security status values were not verified in the captures'),firewall:null,macFilter:null,dmz:null,upnp:null}}}
}
export class HuaweiDriver extends HuaweiClient {}
export class HuaweiDriverFactory{create(){return new HuaweiDriver()}}
