export type CapabilityState='available'|'read-only'|'write-supported'|'unavailable'|'not-exposed-by-firmware'|'requires-additional-HAR'|'local-agent-feature'|'temporarily-unreachable';
export interface Capability {id:string;arabicName:string;englishName:string;icon:string;category:string;state:CapabilityState;readSupported:boolean;writeSupported:boolean;supportSource:'HAR'|'live-router'|'local-agent'|'none';sourceEndpoint:string|null;parserName:string|null;lastVerified:string|null;unsupportedReason:string|null;riskLevel:'low'|'medium'|'high'|'critical';requiresConfirmation:boolean;requiresReauthentication:boolean}
const unavailable='Not exposed by the current router firmware';
const capability=(id:string,arabicName:string,englishName:string,category:string,options:Partial<Capability>={}):Capability=>({id,arabicName,englishName,icon:id,category,state:'not-exposed-by-firmware',readSupported:false,writeSupported:false,supportSource:'none',sourceEndpoint:null,parserName:null,lastVerified:null,unsupportedReason:unavailable,riskLevel:'low',requiresConfirmation:false,requiresReauthentication:false,...options});
export const createCapabilities=(verifiedAt:string|null):Capability[]=>[
 capability('dashboard','لوحة التحكم','Dashboard','general',{state:'available',readSupported:true,supportSource:'live-router',sourceEndpoint:'/api/v1/router/snapshot',parserName:'snapshot',lastVerified:verifiedAt,unsupportedReason:null}),
 capability('devices','الأجهزة المتصلة','Connected Devices','network',{state:'read-only',readSupported:true,supportSource:'live-router',sourceEndpoint:'/html/bbsp/common/GetLanUserDevInfo.asp',parserName:'parseDevices',lastVerified:verifiedAt,unsupportedReason:'Device write actions require additional verified HAR evidence'}),
 capability('wifi','الشبكة اللاسلكية','Wi-Fi Settings','network',{state:'read-only',readSupported:true,supportSource:'HAR',sourceEndpoint:'/html/amp/wlanadv/wlanadvance_api.asp',parserName:'parseWifi',lastVerified:verifiedAt,unsupportedReason:'Wi-Fi writes require post-action live verification',riskLevel:'high',requiresConfirmation:true,requiresReauthentication:true}),
 capability('wan','الإنترنت','WAN / Internet','network',{state:'read-only',readSupported:true,supportSource:'HAR',sourceEndpoint:'/html/bbsp/common/getWanDynamicData.asp',parserName:'parseWan',lastVerified:verifiedAt,unsupportedReason:'WAN writes are not verified',riskLevel:'critical',requiresConfirmation:true,requiresReauthentication:true}),
 capability('device-info','معلومات الجهاز','System','system',{state:'read-only',readSupported:true,supportSource:'HAR',sourceEndpoint:'/html/ssmp/deviceinfo/deviceinfo.asp',parserName:'parseDeviceInfo',lastVerified:verifiedAt,unsupportedReason:'System writes are not verified'}),
 ...[['guest-wifi','شبكة الضيوف','Guest Network','network'],['lan','الشبكة المحلية','LAN','network'],['dhcp','خادم DHCP','DHCP','network'],['dns','نظام أسماء النطاقات','DNS','network'],['nat','ترجمة العناوين','NAT','network'],['port-mappings','تحويل المنافذ','Port Forwarding','network'],['security','مركز الأمان','Security Center','security'],['firewall','الجدار الناري','Firewall','security'],['mac-filter','تصفية MAC','MAC Filtering','security'],['dmz','المنطقة المعزولة','DMZ','security'],['upnp','UPnP','UPnP','security'],['firmware','البرنامج الثابت','Firmware','system'],['backup','النسخ الاحتياطي','Backup & Restore','system']].map(([id,ar,en,cat])=>capability(id,ar,en,cat,{state:'requires-additional-HAR',unsupportedReason:'Additional verified HAR and post-action verification are required'})),
 ...[['diagnostics','التشخيص','Diagnostics'],['monitoring','المراقبة المباشرة','Live Monitoring'],['logs','السجلات','Logs']].map(([id,ar,en])=>capability(id,ar,en,'local',{state:'local-agent-feature',readSupported:true,writeSupported:id==='diagnostics',supportSource:'local-agent',sourceEndpoint:id==='logs'?'/api/v1/logs':`/api/v1/${id}`,parserName:null,lastVerified:verifiedAt,unsupportedReason:null}))
];
