import { Router } from 'express';
import { PollingService } from './polling.js';
import { getRouterRuntimeConfig } from './config.js';
import type { Response } from 'express';
import { createCapabilities } from './capabilities.js';
import type {RouterDatabase} from './storage.js';
import {networkModules,readNetworkModule} from './network/index.js';
import type {NetworkHistoryStore} from './network/history.js';
import {calculateSecurityScore,securityCapabilities,securityFindings,securityModule,securityOverview,securityRecommendations} from './security/security-center.js';
import type {SecurityStore} from './security/security-store.js';
import type {MonitoringStore} from './monitoring/store.js';
import {connectionQuality,liveMetrics,networkHealth} from './monitoring/engine.js';

export const createRouterApi=(service:PollingService,database:RouterDatabase,networkHistory:NetworkHistoryStore,securityStore:SecurityStore,monitoringStore:MonitoringStore)=>{const router=Router(),config=getRouterRuntimeConfig(); const snapshot=(_req:unknown,res:Response)=>{const s=service.getSnapshot();if(!s)return res.status(503).json({supported:false,reason:'No verified router snapshot available'});res.json(s)};
 router.get('/api/v1/router/snapshot',snapshot);router.get('/api/router/snapshot',snapshot);
 for(const [path,key] of [['device-info','deviceInfo'],['health','health'],['wan','wan'],['wifi','wifi'],['security','security']] as const)router.get(`/api/v1/router/${path}`,(_q,res)=>{const s=service.getSnapshot();if(!s)return res.status(503).json({supported:false,reason:'No verified router snapshot available'});res.json(s[key])});
 router.get('/api/v1/router/devices',async(_q,res)=>{const inventory=await service.getInventory();if(!inventory)return res.status(503).json({supported:false,reason:'No verified router snapshot available'});res.json(inventory)});
 router.get('/api/v1/router/devices/:mac/timeline',async(req,res)=>res.json(await database.timeline(req.params.mac.toUpperCase())));
 router.patch('/api/v1/router/devices/:mac/metadata',async(req,res)=>res.json(await database.updateMetadata(req.params.mac.toUpperCase(),req.body as {friendlyName?:string|null;owner?:string|null;notes?:string|null;location?:string|null;favorite?:boolean;tags?:string[]})));
 router.get('/api/v1/router/geo',(_q,res)=>res.status(501).json({supported:false,reason:'Not exposed by current firmware',locationSource:'Unknown'}));
 for(const module of networkModules)router.get(`/api/v1/network/${module}`,(_q,res)=>{let routerIp=config.baseUrl;try{routerIp=new URL(config.baseUrl).hostname}catch{/* configured value retained */}res.json(readNetworkModule(module,service.getSnapshot(),routerIp))});
 router.get('/api/v1/network/:module/history',async(req,res)=>res.json(await networkHistory.history(req.params.module)));
 router.patch('/api/v1/network/:module',(_q,res)=>res.status(501).json({supported:false,reason:'Not supported by current firmware',requiresConfirmation:true}));
 router.get('/api/v1/security/capabilities',(_q,res)=>res.json(securityCapabilities(service.getSnapshot())));
 router.get('/api/v1/security/overview',(_q,res)=>res.json(securityOverview(service.getSnapshot())));
 router.get('/api/v1/security/score',(_q,res)=>res.json(calculateSecurityScore(service.getSnapshot())));
 router.get('/api/v1/security/findings',(_q,res)=>res.json(securityFindings(service.getSnapshot())));
 router.get('/api/v1/security/recommendations',(_q,res)=>res.json(securityRecommendations(service.getSnapshot())));
 for(const module of ['firewall','access-control','mac-filter','parental-control','content-filter','dns','wifi','hardening','alerts','events','audit'])router.get(`/api/v1/security/${module}`,async(_q,res)=>{if(module==='audit')return res.json({module,supported:true,writeSupported:false,verified:true,reason:null,data:{items:await securityStore.audit()}});res.json(securityModule(module,service.getSnapshot()))});
 router.get('/api/v1/security/firewall/rules',(_q,res)=>res.json({supported:false,verified:false,writeSupported:false,reason:'Feature support has not been verified',items:[]}));
 router.get('/api/v1/security/history',async(_q,res)=>res.json({module:'history',supported:true,verified:true,writeSupported:false,reason:null,lastVerified:service.getSnapshot()?.timestamp??null,data:{items:await securityStore.history()}}));
 router.get('/api/v1/monitoring/status',(_q,res)=>{const s=service.getSnapshot(),d=service.getDiagnostics();res.json({collectorState:d.backendState,routerReachable:d.routerReachable,authenticationVerified:d.authenticationVerified,lastSuccessfulPoll:s?.timestamp??null,pollingIntervalMs:config.pollIntervalMs,classification:s?'measured':'unavailable'})});
 router.get('/api/v1/monitoring/live',(_q,res)=>res.json({version:1,metrics:liveMetrics(service.getSnapshot(),monitoringStore.getRates())}));router.get('/api/v1/monitoring/metrics',(_q,res)=>res.json(liveMetrics(service.getSnapshot(),monitoringStore.getRates())));
 router.get('/api/v1/monitoring/metrics/:metricKey/history',async(req,res)=>res.json({metricKey:req.params.metricKey,items:await monitoringStore.history(req.params.metricKey==='publicIp'?'public-ip':req.params.metricKey==='traffic'?'traffic':'availability')}));
 router.get('/api/v1/monitoring/traffic/wan',async(_q,res)=>res.json({supported:service.getSnapshot()?.wan.downloadBytes!=null,classification:'derived',formula:'byte delta × 8 / time delta',current:monitoringStore.getRates(),items:await monitoringStore.history('traffic')}));
 for(const scope of ['interfaces','devices'])router.get(`/api/v1/monitoring/traffic/${scope}`,(_q,res)=>res.json({supported:false,classification:'unsupported',reason:'Not exposed by current firmware',items:[]}));
 router.get('/api/v1/monitoring/availability',async(_q,res)=>res.json({classification:'measured',items:await monitoringStore.history('availability')}));router.get('/api/v1/monitoring/health',(_q,res)=>res.json(networkHealth(service.getSnapshot())));router.get('/api/v1/monitoring/quality',(_q,res)=>res.json(connectionQuality(service.getSnapshot())));
 router.get('/api/v1/monitoring/public-ip/history',async(_q,res)=>res.json({classification:'measured',items:await monitoringStore.history('public-ip')}));router.get('/api/v1/monitoring/events',async(_q,res)=>res.json({items:await monitoringStore.events()}));router.get('/api/v1/monitoring/alerts',async(_q,res)=>res.json({items:await monitoringStore.alerts()}));router.get('/api/v1/monitoring/alert-rules',async(_q,res)=>res.json({items:await monitoringStore.rules()}));
 router.get('/api/v1/monitoring/diagnostics',async(_q,res)=>res.json({pollingIntervalMs:config.pollIntervalMs,overlappingCycles:false,sessionReuse:true,queueDepth:0,history:await monitoringStore.diagnostics(),secretsExposed:false}));router.get('/api/v1/monitoring/export',async(req,res)=>{const kind=String(req.query.kind??'traffic'),items=await monitoringStore.history(kind==='public-ip'?'public-ip':kind==='availability'?'availability':'traffic');res.json({exportedAt:new Date().toISOString(),timezone:String(req.query.timezone??'UTC'),classification:kind==='traffic'?'derived':'measured',source:'Adil RouterOS verified monitoring history',missingDataPreserved:true,items})});
 const invalidRule=(_q:unknown,res:Response)=>res.status(501).json({code:'INVALID_ALERT_RULE',reason:'Alert rule writes require a separately verified configuration workflow'});router.post('/api/v1/monitoring/alert-rules',invalidRule);router.patch('/api/v1/monitoring/alert-rules/:id',invalidRule);router.delete('/api/v1/monitoring/alert-rules/:id',invalidRule);router.patch('/api/v1/monitoring/alerts/:id',invalidRule);
 router.post('/api/v1/router/auth',async(req,res)=>{const {username,password}=req.body as {username?:string,password?:string};if(!username||!password)return res.status(400).json({status:'failed',reason:'Username and password required'});try{await service.start(username,password);res.json({status:'connected',reason:null})}catch(e){const m=e instanceof Error?e.message:'Authentication failed';res.status(/protocol/i.test(m)?409:401).json({status:/protocol/i.test(m)?'protocol-mismatch':'failed',reason:m})}});
 router.post('/api/v1/router/refresh',async(_q,res)=>{try{res.json(await service.refresh())}catch(e){res.status(503).json({reason:e instanceof Error?e.message:'Refresh failed'})}});
 router.post('/api/v1/router/logout',(_q,res)=>{service.stop();res.json({status:'disconnected'})});
 router.get('/api/v1/router/diagnostics',(_q,res)=>res.json(service.getDiagnostics()));router.get('/api/v1/router/capabilities',(_q,res)=>res.json(createCapabilities(service.getSnapshot()?.timestamp??null)));
 router.get('/api/v1/router/auth-diagnostics',(_q,res)=>res.json(service.getAuthDiagnostics()));
 router.get('/api/v1/router/config',(_q,res)=>res.json({routerAddress:config.baseUrl,pollingInterval:config.pollIntervalMs,backendVersion:'v4.0.0',sessionStatus:service.getDiagnostics().authenticationVerified?'verified':'not verified'}));
 router.get('/api/v1/logs',(_q,res)=>res.json(service.getLogs()));
 router.get('/api/v1/router/logs',(_q,res)=>res.json(service.getLogs()));
 const unsupported=(_q:unknown,res:Response)=>res.status(501).json({supported:false,reason:'Not exposed by the current router firmware'});
 router.post('/api/v1/router/devices/:mac/block',unsupported);
 router.post('/api/v1/router/devices/:mac/unblock',unsupported);
 router.put('/api/v1/router/wifi',unsupported);
 router.post('/api/v1/router/reboot',unsupported);
 router.post('/api/v1/router/port-mappings',unsupported);
 router.put('/api/v1/router/port-mappings/:id',unsupported);
 router.delete('/api/v1/router/port-mappings/:id',unsupported);
 for(const path of ['guest-wifi','lan','dhcp','dhcp/reservations','firewall','mac-filter','dmz','upnp','port-mappings','parental-controls','content-rules'])router.get(`/api/v1/router/${path}`,(req,res)=>{const id=req.path.split('/').filter(Boolean).pop()??path;res.status(501).json({supported:false,reason:'Not exposed by the current router firmware',capability:id})});
 return router};
