import type {RouterSnapshot} from '../types.js';
export type Classification='measured'|'derived'|'estimated'|'unavailable'|'unsupported'|'stale';
export interface Metric<T=number|string|boolean|null>{value:T;unit:string|null;source:string;classification:Classification;collectedAt:string|null;ageMs:number|null;stale:boolean;confidence:'high'|'medium'|'low';supported:boolean}
const metric=<T>(value:T,unit:string|null,source:string,classification:Classification,at:string|null,supported=true):Metric<T>=>{const ageMs=at?Math.max(0,Date.now()-Date.parse(at)):null,stale=ageMs!=null&&ageMs>60_000;return{value,unit,source,classification:stale?'stale':classification,collectedAt:at,ageMs,stale,confidence:classification==='measured'?'high':classification==='derived'?'medium':'low',supported}};
export interface CounterPoint{at:string;rx:number|null;tx:number|null}
export const counterDelta=(previous:CounterPoint|null,current:CounterPoint)=>{if(!previous||current.rx==null||current.tx==null||previous.rx==null||previous.tx==null)return null;const elapsed=(Date.parse(current.at)-Date.parse(previous.at))/1000;if(elapsed<=0)return null;const delta=(now:number,before:number)=>now>=before?now-before:null;const rx=delta(current.rx,previous.rx),tx=delta(current.tx,previous.tx);if(rx==null||tx==null)return null;return{seconds:elapsed,rxBytes:rx,txBytes:tx,downloadBps:rx*8/elapsed,uploadBps:tx*8/elapsed}};
export const liveMetrics=(s:RouterSnapshot|null,rates:{downloadBps:number;uploadBps:number}|null)=>{const at=s?.timestamp??null,source=s?.wan.sourceEndpoint??'Huawei verified snapshot';return{routerReachable:metric(s!=null,null,'Authenticated polling snapshot',s?'measured':'unavailable',at,!!s),authentication:metric(s?.authentication.status??null,null,s?.authentication.verifiedEndpoint??'Protected endpoint verification',s?'measured':'unavailable',at,!!s),uptime:metric(s?.deviceInfo.uptime??null,'s',s?.deviceInfo.sourceEndpoint??'Huawei device information',s?.deviceInfo.uptime!=null?'measured':'unsupported',at,s?.deviceInfo.uptime!=null),publicIp:metric(s?.wan.ip??null,null,source,s?.wan.ip?'measured':'unavailable',at,s?.wan.supported??false),wanState:metric(s?.wan.state??null,null,source,s?.wan.state?'measured':'unavailable',at,s?.wan.supported??false),receivedBytes:metric(s?.wan.downloadBytes??null,'bytes',source,s?.wan.downloadBytes!=null?'measured':'unsupported',at,s?.wan.downloadBytes!=null),transmittedBytes:metric(s?.wan.uploadBytes??null,'bytes',source,s?.wan.uploadBytes!=null?'measured':'unsupported',at,s?.wan.uploadBytes!=null),downloadRate:metric(rates?.downloadBps??null,'bps','Derived from consecutive Huawei WAN byte counters',rates?'derived':'unavailable',at,!!rates),uploadRate:metric(rates?.uploadBps??null,'bps','Derived from consecutive Huawei WAN byte counters',rates?'derived':'unavailable',at,!!rates),connectedDevices:metric(s?.devices.items.filter(x=>x.online!==false).length??null,'devices',s?.devices.sourceEndpoint??'Huawei connected devices',s?.devices.supported?'measured':'unsupported',at,s?.devices.supported??false),wifiRadios:(s?.wifi.bands??[]).map(x=>({ssid:x.ssid,band:x.band,enabled:metric(x.enabled,null,s?.wifi.sourceEndpoint??'Huawei Wi-Fi parser',x.enabled==null?'unavailable':'measured',at,s?.wifi.supported??false),channel:metric(x.channel,'channel',s?.wifi.sourceEndpoint??'Huawei Wi-Fi parser',x.channel==null?'unsupported':'measured',at,x.channel!=null)}))}};
export const networkHealth=(s:RouterSnapshot|null)=>{const components=[{name:'Router reachability',available:!!s,pass:!!s,evidence:s?.timestamp??null},{name:'Authentication stability',available:!!s,pass:s?.authentication.status==='connected',evidence:s?.authentication.verifiedEndpoint??null},{name:'WAN connection',available:!!s?.wan.state,pass:/connected|up/i.test(s?.wan.state??''),evidence:s?.wan.sourceEndpoint??null},{name:'Collection freshness',available:!!s,pass:s?Date.now()-Date.parse(s.timestamp)<60_000:false,evidence:s?.timestamp??null}];const assessed=components.filter(x=>x.available),score=assessed.length?Math.round(assessed.filter(x=>x.pass).length/assessed.length*100):null;return{score,kind:assessed.length===components.length?'full':'partial',confidence:assessed.length>=4?'high':assessed.length>=2?'medium':'low',componentsAssessed:assessed.length,componentsUnavailable:components.length-assessed.length,components,calculatedAt:new Date().toISOString()}};
export const connectionQuality=(s:RouterSnapshot|null)=>({supported:false,score:null,reason:'Insufficient measurements to calculate connection quality',devices:(s?.devices.items??[]).map(x=>({mac:x.mac,hostname:x.hostname,score:null,reason:'Insufficient measurements to calculate connection quality'}))});
export interface AlertRule{id:string;enabled:boolean;operator:'gt'|'gte'|'lt'|'lte'|'eq';threshold:number;cooldownMs:number}
export const evaluateAlert=(rule:AlertRule,value:number|null,fresh:boolean)=>{if(!rule.enabled||value==null||!fresh)return false;return rule.operator==='gt'?value>rule.threshold:rule.operator==='gte'?value>=rule.threshold:rule.operator==='lt'?value<rule.threshold:rule.operator==='lte'?value<=rule.threshold:value===rule.threshold};
export const mergeAlertOccurrence=(existing:{occurrenceCount:number;lastDetected:string}|null,detectedAt:string,cooldownMs:number)=>existing&&Date.parse(detectedAt)-Date.parse(existing.lastDetected)<cooldownMs?{...existing,lastDetected:detectedAt}:{occurrenceCount:(existing?.occurrenceCount??0)+1,lastDetected:detectedAt};
