import {useEffect,useState} from 'react';import {State} from './shared.js';
type Overview={router:{backendState:string;routerReachable:boolean;authenticationVerified:boolean};recentRuns:Array<{id:string;type:string;target:string;status:string}>;capabilities:Record<string,{supported:boolean;source:string;limitations:string}>};
export const DiagnosticsPage=({tool='overview'}:{tool?:'overview'|'ping'|'dns'})=>{
 const [data,setData]=useState<Overview|null>(null),[target,setTarget]=useState(tool==='dns'?'example.com':'192.168.1.1'),[result,setResult]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[running,setRunning]=useState(false);
 const refresh=()=>fetch('/api/v1/diagnostics/overview').then(r=>r.json()).then(setData).catch(()=>setError('Diagnostics are unavailable'));useEffect(()=>{refresh()},[]);
 const run=async()=>{setRunning(true);setError(null);try{const path=tool==='dns'?'dns':'ping',body=tool==='dns'?{query:target,type:'A'}:{target,count:4,timeoutMs:3000},response=await fetch(`/api/v1/diagnostics/${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),json=await response.json();if(!response.ok)throw new Error(json.message??'Diagnostic failed');setResult(JSON.stringify(json,null,2));refresh()}catch(e){setError(e instanceof Error?e.message:'Diagnostic failed')}finally{setRunning(false)}};
 if(!data)return <State loading={!error} error={error}/>;
 return <div className="page-stack"><section className="hero"><div><p className="eyebrow">Diagnostics Suite</p><h2>{tool==='overview'?'Diagnostics overview':tool==='dns'?'DNS lookup':'Safe ping'}</h2><p>Real measurements, strict target validation, bounded execution, and sanitized history.</p></div></section><section className="metrics-grid">{[['Backend',data.router.backendState],['Router',data.router.routerReachable?'Reachable':'Unavailable'],['Authentication',data.router.authenticationVerified?'Verified':'Not verified']].map(([name,value])=><article className="metric-card" key={name}><p>{name}</p><strong>{value}</strong><span className="status good">measured</span></article>)}</section>{tool!=='overview'&&<section className="panel"><h3>Target</h3><div className="flex gap-3"><input aria-label="Diagnostic target" className="input flex-1" value={target} onChange={e=>setTarget(e.target.value)} maxLength={253}/><button className="button" disabled={running} onClick={run}>{running?'Running…':'Run diagnostic'}</button></div>{error&&<p role="alert" className="text-red-300">{error}</p>}{result!==null&&<pre className="mt-4 overflow-auto rounded-xl bg-black/30 p-4 text-xs">{result}</pre>}</section>}<section className="panel"><h3>Capabilities</h3><div className="metrics-grid">{Object.entries(data.capabilities).map(([name,c])=><article className="metric-card" key={name}><p>{name}</p><strong>{c.supported?'Supported':'Unsupported'}</strong><small>{c.source} · {c.limitations}</small></article>)}</div></section><section className="panel"><h3>Recent real runs</h3>{data.recentRuns.length?data.recentRuns.map(item=><div className="flex justify-between border-b border-white/10 py-3" key={item.id}><span>{item.type} · {item.target}</span><span>{item.status}</span></div>):<div className="empty-state">No diagnostics have been run yet</div>}</section></div>;
};
