export interface SupportMeta { supported:boolean; reason:string|null; sourceEndpoint:string|null; lastUpdated:string|null }
export interface RouterDevice { hostname:string|null; alias:string|null; ipv4:string|null; ipv6:string|null; mac:string|null; connectionType:string|null; wifiBand:string|null; signal:number|null; online:boolean|null; connectionDuration:number|null }
export interface IntelligentDevice extends RouterDevice {uniqueId:string;friendlyName:string|null;vendor:string|null;manufacturer:string|null;oui:string|null;model:string|null;type:string;operatingSystem:string|null;evidence:string[];confidence:string;wireless:boolean;wired:boolean;band:string|null;rssi:number|null;noise:number|null;snr:number|null;linkSpeed:number|null;txRate:number|null;rxRate:number|null;channel:number|null;bandwidth:number|null;connectedSince:string|null;sessionDuration:number|null;upload:number|null;download:number|null;totalUsage:number|null;packets:number|null;dhcpLease:string|null;staticIp:boolean|null;gateway:string|null;dns:string[]|null;authenticationState:string|null;blocked:boolean;whitelisted:boolean;firstSeen:string;lastSeen:string;onlineCount:number;offlineCount:number;longestSession:number|null;averageSession:number|null;favorite:boolean;owner:string|null;location:string|null;notes:string|null;tags:string[];geo:null;unsupportedReason:string}
export interface DeviceTimelineEvent{id:number;at:string;event:string;previousValue:string|null;currentValue:string|null}
export interface RouterSnapshot { timestamp:string; stale:boolean; authentication:{status:string;reason:string|null;verifiedEndpoint:string|null}; deviceInfo:SupportMeta&{model:string|null;firmware:string|null;serial:string|null;hardwareVersion:string|null;uptime:number|null}; health:SupportMeta&{cpuUsage:number|null;memoryUsage:number|null;temperature:number|null}; wan:SupportMeta&{state:string|null;ip:string|null;gateway:string|null;dns:string[]|null;connectionType:string|null;uptime:number|null;uploadBytes:number|null;downloadBytes:number|null}; wifi:SupportMeta&{bands:Array<{band:string;ssid:string|null;enabled:boolean|null;channel:number|null;security:string|null;guest:boolean}>}; devices:SupportMeta&{items:RouterDevice[]}; security:SupportMeta&{firewall:boolean|null;macFilter:boolean|null;dmz:boolean|null;upnp:boolean|null} }
export interface RouterConfig { routerAddress:string; pollingInterval:number; backendVersion:string; sessionStatus:string }
export interface Diagnostics { backendState:string;routerReachable:boolean;authenticationVerified:boolean;lastSuccessfulEndpoint:string|null;failedEndpoint:string|null;httpStatus:number|null;parserName:string|null;safeReason:string|null;lastPollTime:string|null;snapshotAge:number|null }
export const uniqueDevices=(items:RouterDevice[])=>[...new Map(items.map((item,index)=>[item.mac??item.ipv4??`${index}`,item])).values()];
export const firmwareReason=(reason:string|null)=>reason??'Not supported by firmware';
export const formatDuration=(seconds:number|null)=>{if(seconds==null)return null;const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return [days&&`${days}d`,hours&&`${hours}h`,minutes&&`${minutes}m`,`${seconds%60}s`].filter(Boolean).join(' ')};
