import axios from 'axios';
import { useCallback, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

export const useApi=<T,>(path:string)=>{const [data,setData]=useState<T|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{setData((await axios.get<T>(path)).data);setError(null)}catch(e){setError(axios.isAxiosError(e)?e.response?.data?.reason??e.message:'Request failed')}finally{setLoading(false)}},[path]);useEffect(()=>{void load()},[load]);return{data,error,loading,reload:load}};
export const Page=({title,description,children}:{title:string;description?:string;children:ReactNode})=><section className="space-y-5"><header><h2 className="text-2xl font-semibold text-emerald-200">{title}</h2>{description&&<p className="mt-1 text-sm text-[#7d9580]">{description}</p>}</header>{children}</section>;
export const Card=({title,value,reason,source}:{title:string;value:ReactNode;reason?:string|null;source?:string|null})=><div className="rounded-2xl border border-emerald-900/60 bg-[#07120d] p-4"><p className="text-xs text-emerald-600">{title}</p><div className="mt-2 text-lg text-emerald-100">{value}</div>{reason&&<p className="mt-2 text-xs text-amber-300">{reason}</p>}{source&&<p className="mt-3 break-all text-[10px] text-emerald-800">{source}</p>}</div>;
export const unavailable='غير متاح من إصدار الراوتر الحالي';
export const Value=({value}:{value:ReactNode|null|undefined;supported?:boolean;reason?:string|null})=>value!=null&&value!==''?<>{value}</>:<span className="text-sm text-[#7d9580]">{unavailable}</span>;
export const State=({loading,error}:{loading:boolean;error:string|null})=>loading?<div role="status" className="grid gap-3"><div className="h-24 animate-pulse rounded-2xl bg-emerald-950/40"/><p className="text-sm text-emerald-500">جارٍ تحميل بيانات الراوتر المباشرة…</p></div>:error?<div role="alert" className="rounded-2xl border border-rose-900/60 bg-rose-950/30 p-4 text-rose-200">تعذر تحديث بيانات الراوتر بأمان.</div>:null;
export const Empty=({children}:{children:ReactNode})=><div className="rounded-2xl border border-dashed border-emerald-900 p-8 text-center text-[#7d9580]">{children}</div>;
