import axios from 'axios';
import { useCallback, useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import {useLanguage} from '../i18n.js';

export const useApi=<T,>(path:string)=>{const [data,setData]=useState<T|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{setData((await axios.get<T>(path)).data);setError(null)}catch(e){setError(axios.isAxiosError(e)?e.response?.data?.reason??e.message:'Request failed')}finally{setLoading(false)}},[path]);useEffect(()=>{void load()},[load]);return{data,error,loading,reload:load}};
export const Page=({title,description,children}:{title:string;description?:string;children:ReactNode})=><section className="space-y-5"><header className="border-b border-[var(--border)] pb-4"><h2 className="text-2xl font-semibold text-[var(--text-primary)]">{title}</h2>{description&&<p className="mt-1 text-sm text-[var(--text-secondary)]">{description}</p>}</header>{children}</section>;
export const Card=({title,value,reason,source}:{title:string;value:ReactNode;reason?:string|null;source?:string|null})=><article className="surface-card p-4"><p className="text-xs font-medium text-[var(--text-secondary)]">{title}</p><div className="mt-2 text-lg text-[var(--text-primary)]">{value}</div>{reason&&<details className="mt-3 text-xs text-amber-300"><summary>Technical details</summary><p>{reason}</p></details>}{source&&<details className="mt-2 break-all text-[10px] text-[var(--text-secondary)]"><summary>Data source</summary>{source}</details>}</article>;
export const unavailable='غير متاح من إصدار الراوتر الحالي';
export const Value=({value}:{value:ReactNode|null|undefined;supported?:boolean;reason?:string|null})=>value!=null&&value!==''?<>{value}</>:<span className="text-sm text-[#7d9580]">{unavailable}</span>;
export const State=({loading,error}:{loading:boolean;error:string|null})=>{const {t}=useLanguage();return loading?<div role="status" aria-live="polite" className="grid gap-3"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{[0,1,2].map(i=><div key={i} className="h-24 animate-pulse rounded-2xl border border-[var(--border)] bg-white/[.03]"/>)}</div><p className="text-sm text-[var(--text-secondary)]">{t('loading')}</p></div>:error?<div role="alert" className="rounded-2xl border border-rose-900/60 bg-rose-950/30 p-4 text-rose-200">{t('loadError')}</div>:null};
export const Empty=({children}:{children:ReactNode})=><div className="rounded-2xl border border-dashed border-emerald-900 p-8 text-center text-[#7d9580]">{children}</div>;
