import type {RouterSnapshot} from '../types.js';
export const unsupported='Not supported by the current firmware';export const unverified='Feature support has not been verified';
const sensitiveKey=/password|passwd|cookie|authorization|token|session|credential|secret/i;
export const redactSecurityData=(value:unknown):unknown=>{
  if(Array.isArray(value))return value.map(redactSecurityData);
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,sensitiveKey.test(key)?'[REDACTED]':redactSecurityData(item)]));
  return value;
};
export interface SecurityCapability{supported:boolean;verified:boolean;readOnly:boolean;sourceEndpoint:string|null;parser:string|null;lastVerified:string|null;reason:string|null}
const capability=(supported:boolean,sourceEndpoint:string|null,parser:string|null,lastVerified:string|null,reason:string|null=null):SecurityCapability=>({supported,verified:supported,readOnly:true,sourceEndpoint,parser,lastVerified,reason:supported?reason:reason??unverified});
export const securityCapabilities=(s:RouterSnapshot|null)=>({firewallRead:capability(s?.security.supported===true,s?.security.sourceEndpoint??null,null,s?.timestamp??null,s?.security.reason),firewallWrite:capability(false,null,null,null,unverified),firewallRulesRead:capability(false,null,null,null,unverified),firewallRulesWrite:capability(false,null,null,null,unverified),macFilteringRead:capability(false,null,null,null,unverified),macFilteringWrite:capability(false,null,null,null,unverified),deviceBlocking:capability(false,null,null,null,unverified),parentalControlRead:capability(false,null,null,null,unsupported),parentalControlWrite:capability(false,null,null,null,unsupported),contentFilteringRead:capability(false,null,null,null,unsupported),contentFilteringWrite:capability(false,null,null,null,unsupported),dnsSecurityRead:capability(Array.isArray(s?.wan.dns)&&s!.wan.dns!.length>0,s?.wan.sourceEndpoint??null,'parseWan',s?.timestamp??null),wifiSecurityRead:capability(s?.wifi.supported===true,s?.wifi.sourceEndpoint??null,'parseWifi',s?.timestamp??null),routerManagementProtected:capability(s?.authentication.status==='connected',s?.authentication.verifiedEndpoint??null,'authentication verification',s?.timestamp??null),firmwareInformation:capability(!!s?.deviceInfo.firmware,s?.deviceInfo.sourceEndpoint??null,'parseDeviceInfo',s?.timestamp??null)});
export interface ScoreItem{id:string;name:string;weight:number;verified:boolean;actualStatus:'pass'|'risk'|'unknown';evidenceSource:string|null;explanation:string;recommendation:string;timestamp:string|null}
export const calculateSecurityScore=(s:RouterSnapshot|null)=>{const items:ScoreItem[]=[{id:'management-auth',name:'Router web management protected',weight:20,verified:s?.authentication.status==='connected',actualStatus:s?.authentication.status==='connected'?'pass':'unknown',evidenceSource:s?.authentication.verifiedEndpoint??null,explanation:'Protected router page required a verified authenticated session.',recommendation:'Keep router administration credentials private.',timestamp:s?.timestamp??null},{id:'firmware-visible',name:'Firmware information available',weight:5,verified:!!s?.deviceInfo.firmware,actualStatus:s?.deviceInfo.firmware?'pass':'unknown',evidenceSource:s?.deviceInfo.sourceEndpoint??null,explanation:'Firmware version visibility supports maintenance assessment; freshness is not inferred.',recommendation:'Compare firmware with the ISP-supported release process.',timestamp:s?.timestamp??null},{id:'firewall',name:'Firewall enabled',weight:20,verified:s?.security.firewall!=null,actualStatus:s?.security.firewall==null?'unknown':s.security.firewall?'pass':'risk',evidenceSource:s?.security.sourceEndpoint??null,explanation:s?.security.firewall==null?unverified:'Firewall state reported by router.',recommendation:'Verify firewall support with a firmware capture.',timestamp:s?.timestamp??null},{id:'wifi-encryption',name:'Strong Wi-Fi encryption',weight:20,verified:(s?.wifi.bands??[]).some(x=>x.security!=null),actualStatus:'unknown',evidenceSource:s?.wifi.sourceEndpoint??null,explanation:'Encryption mode is not exposed by the current verified parser response.',recommendation:'Review encryption in the ISP router interface.',timestamp:s?.timestamp??null}];const verified=items.filter(x=>x.verified),possible=verified.reduce((n,x)=>n+x.weight,0),earned=verified.filter(x=>x.actualStatus==='pass').reduce((n,x)=>n+x.weight,0);return{kind:'partial',score:possible?Math.round(earned/possible*100):null,verifiedControls:verified.length,totalAssessedControls:items.length,confidence:verified.length>=8?'high':verified.length>=4?'medium':'low',message:verified.length<items.length?'Insufficient verified data to calculate a complete security score':null,items}};
export const securityFindings=(s:RouterSnapshot|null)=>calculateSecurityScore(s).items.filter(x=>x.verified&&x.actualStatus==='risk').map(x=>({id:x.id,severity:x.weight>=20?'high':'medium',title:x.name,evidence:x.explanation,source:x.evidenceSource,timestamp:x.timestamp}));
export const securityRecommendations=(s:RouterSnapshot|null)=>{const score=calculateSecurityScore(s);return score.items.filter(x=>x.actualStatus==='risk'||!x.verified).map(x=>({finding:x.name,evidence:x.explanation,risk:x.verified?'Verified configuration risk':'Unknown until verified',recommendedAction:x.recommendation,expectedImpact:'Improves visibility or reduces verified exposure',automaticRemediationSupported:false,reversalMethod:'No automatic change is performed',confidenceLevel:x.verified?'high':'low'}))};
export const securityOverview=(s:RouterSnapshot|null)=>({score:calculateSecurityScore(s),firewall:s?.security.firewall??null,wifi:(s?.wifi.bands??[]).map(x=>({ssid:x.ssid,radio:x.band,enabled:x.enabled,encryption:x.security,assessment:x.security==null?'unknown':/wep|wpa(?!2|3)|tkip/i.test(x.security)?'risk':'secure',evidence:s?.wifi.sourceEndpoint??null})),dns:{servers:s?.wan.dns??null,source:s?.wan.sourceEndpoint??null,doh:null,dot:null,filtering:null},accessControl:null,macFiltering:s?.security.macFilter??null,guestIsolation:null,upnp:s?.security.upnp??null,dmz:s?.security.dmz??null,wps:null,remoteAdministration:null,alerts:[],findings:securityFindings(s),recommendations:securityRecommendations(s),lastVerified:s?.timestamp??null});
export const securityModule=(name:string,s:RouterSnapshot|null)=>{const overview=securityOverview(s);const data:Record<string,unknown>={firewall:{enabled:overview.firewall,rules:null},'access-control':{state:null,devices:[]},'mac-filter':{mode:null,entries:null},'parental-control':{profiles:null},'content-filter':{rules:null,limitation:'Domain, DNS, URL, and content-category filtering are distinct capabilities.'},dns:overview.dns,wifi:{radios:overview.wifi},hardening:{firmware:s?.deviceInfo.firmware??null,httpManagement:null,httpsManagement:null,remoteManagement:null,telnet:null,ssh:null,ftp:null,upnp:overview.upnp,dmz:overview.dmz,wps:overview.wps},alerts:{items:overview.alerts},events:{items:[]},audit:{items:[]}};const value=data[name]??{state:null};const supported=name==='dns'?overview.dns.servers!=null:name==='wifi'?s?.wifi.supported===true:name==='hardening'?!!s?.deviceInfo.firmware:false;return{module:name,supported,writeSupported:false,verified:supported,reason:supported?null:unverified,lastVerified:s?.timestamp??null,data:value}};
